# Generated by Django 4.0.6 on 2022-07-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='author',
            new_name='customer',
        ),
    ]
