# Generated by Django 4.0.6 on 2022-07-26 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_author_productcomment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
    ]
